language: c

os:
 - linux

compiler:
 - clang
 - gcc
 - g++

sudo: required
dist: trusty

addons:
  apt:
    packages:
    - libjack-jackd2-dev
    - libsndfile1-dev
    - libsoxr-dev
    - libgtk-3-dev

before_script:
 - autoreconf -ivf
